
target 'notifizer' do
  rn_path = '../node_modules/react-native'
  platform :ios, '9.0'
  # Very IMPORTANT to have, unless you removed React dependencies for Libraries 
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
#      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'


end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "React"
          target.remove_from_project
      end
  end
end
